import { describe, expect, it } from "vitest";
import {
  allowedMapdownOrigin,
  createMapdownHandoff,
  hashMapdownNonce
} from "../../../web/app/utils/mapdown-handoff.server";
import { ApiError } from "./http";
import { verifyMapdownHandoff } from "./handoff";
import { serializeMapdownSessionCookie } from "./session";
import {
  validateCloudSnapshot,
  validatePublishedMarkdown,
  validatePublishedSvg
} from "./validation";
import { createDocument, SCHEMA_VERSION } from "../../src/model/types";

const SECRET = "test-secret-with-enough-entropy-for-a-contract-test";
const AUDIENCE = "https://map.bcailab.com";
const NOW = Date.UTC(2026, 7, 21, 12);
const NONCE = "123e4567-e89b-12d3-a456-426614174000";

describe("Mapdown sign-in handoff", () => {
  it("round-trips a short-lived, audience-bound token and nonce digest", async () => {
    const created = await createMapdownHandoff({
      secret: SECRET,
      userId: "user-1",
      audience: AUDIENCE,
      nowMs: NOW,
      nonce: NONCE
    });
    const verified = await verifyMapdownHandoff({
      secret: SECRET,
      token: created.token,
      audience: AUDIENCE,
      nowMs: NOW + 59_000
    });

    expect(verified).toMatchObject({ userId: "user-1", nonce: NONCE, audience: AUDIENCE });
    expect(created.nonceHash).toBe(await hashMapdownNonce(NONCE));
  });

  it("rejects tampering, expiry, and a different audience", async () => {
    const { token } = await createMapdownHandoff({
      secret: SECRET,
      userId: "user-1",
      audience: AUDIENCE,
      nowMs: NOW,
      nonce: NONCE
    });

    await expect(verifyMapdownHandoff({
      secret: SECRET,
      token: `${token.slice(0, -1)}x`,
      audience: AUDIENCE,
      nowMs: NOW
    })).rejects.toThrow("invalid handoff");
    await expect(verifyMapdownHandoff({
      secret: SECRET,
      token,
      audience: "http://localhost:5173",
      nowMs: NOW
    })).rejects.toThrow("invalid handoff");
    await expect(verifyMapdownHandoff({
      secret: SECRET,
      token,
      audience: AUDIENCE,
      nowMs: NOW + 61_000
    })).rejects.toThrow("expired handoff");
  });

  it("allows only the production app origin and local HTTP development", () => {
    expect(allowedMapdownOrigin("https://map.bcailab.com")).toBe(AUDIENCE);
    expect(allowedMapdownOrigin("http://localhost:5173")).toBe("http://localhost:5173");
    expect(allowedMapdownOrigin("https://evil.example")).toBeNull();
    expect(allowedMapdownOrigin("https://map.bcailab.com/attacker-path")).toBeNull();
  });
});

describe("Mapdown cloud contracts", () => {
  it("accepts a valid lossless snapshot and rejects inconsistent trees", async () => {
    const document = { ...createDocument("Root"), title: "Roadmap" };
    const snapshot = { schemaVersion: SCHEMA_VERSION, document, selectedNodeId: document.rootId };
    const validated = await validateCloudSnapshot(snapshot);

    expect(validated.nodeCount).toBe(1);
    expect(validated.snapshot).toEqual(snapshot);
    await expect(validateCloudSnapshot({
      ...snapshot,
      document: {
        ...document,
        nodes: {
          ...document.nodes,
          [document.rootId]: { ...document.nodes[document.rootId], childIds: ["missing"] }
        }
      }
    })).rejects.toMatchObject({ status: 400, code: "snapshot" });
  });

  it("requires canonical Markdown and a safe exporter SVG", () => {
    expect(validatePublishedMarkdown("# Root\n")).toBe("# Root\n");
    expect(() => validatePublishedMarkdown("---\nshape: pill\n# Root\n")).toThrow(ApiError);
    expect(validatePublishedSvg(
      '<svg xmlns="http://www.w3.org/2000/svg"><desc>Generated by Mapdown</desc></svg>'
    )).toContain("Generated by Mapdown");
    expect(() => validatePublishedSvg(
      '<svg xmlns="http://www.w3.org/2000/svg"><desc>Generated by Mapdown</desc><script>alert(1)</script></svg>'
    )).toThrow(ApiError);
  });

  it("keeps the Mapdown session host-only and secure in production", () => {
    const production = serializeMapdownSessionCookie(
      new Request("https://map.bcailab.com/api/session"),
      "token",
      60
    );
    expect(production).toContain("HttpOnly");
    expect(production).toContain("SameSite=Lax");
    expect(production).toContain("Secure");
    expect(production).not.toContain("Domain=");

    const local = serializeMapdownSessionCookie(
      new Request("http://localhost:5173/api/session"),
      "token",
      60
    );
    expect(local).not.toContain("Secure");
  });
});
