name = "bcailab-session-cleanup"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[triggers]
crons = ["17 3 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "bcailab-db"
database_id = "7048b3f2-affb-492a-a9a4-18ab5cd2fc4e"
preview_database_id = "8707dea1-f2f7-4a3c-99ee-2245cb63e22c"
