import { beforeEach, describe, expect, it } from "vitest";
import kepanSource from "../fixtures/kepan.md?raw";
import { clearMeasurementCache } from "../layout/measure";
import { importMarkdown } from "../markdown/parse";
import { exportMarkdown } from "../markdown/serialize";
import { applyCommand } from "../model/commands";
import { createDocument, getNode, resetIdCounterForTests, type MindMapDocument } from "../model/types";
import { PALETTES, SHAPES, resolveTheme } from "../theme/presets";
import { MAX_CANVAS_AREA, pixelDimensions, resolveScale } from "./png";
import { exportSvg } from "./svg";
import { escapeXml } from "./xml";

beforeEach(() => {
  resetIdCounterForTests();
  clearMeasurementCache();
});

function build(labels: [string, number][]): MindMapDocument {
  let doc = createDocument(labels[0]![0]);
  const atDepth: string[] = [doc.rootId];
  for (const [text, depth] of labels.slice(1)) {
    const result = applyCommand(doc, { type: "CreateChild", parentId: atDepth[depth - 1]!, text });
    doc = result.doc;
    atDepth[depth] = result.selection!;
    atDepth.length = depth + 1;
  }
  return doc;
}

const kepan = () => {
  const result = importMarkdown(kepanSource);
  if (!result.ok) throw new Error(result.error);
  return result.doc;
};

describe("§12.3 / §12.6 — the file is self-contained and inert", () => {
  it.each(SHAPES)("$name emits no script, foreignObject or external reference", (shape) => {
    const doc: MindMapDocument = {
      ...kepan(),
      theme: { shapeId: shape.id, paletteId: shape.defaultPaletteId, branchColorMode: "by-first-level-branch" }
    };
    const { svg } = exportSvg(doc);

    expect(svg).not.toMatch(/<script/i);
    expect(svg).not.toMatch(/<foreignObject/i);
    expect(svg).not.toMatch(/xlink:href|<image\b/i);
    expect(svg).not.toMatch(/@import|url\(\s*['"]?https?:/i);
    // A web font would be the one external dependency that looks harmless and vanishes on
    // rasterisation — spike 2, Finding 3.
    expect(svg).not.toMatch(/@font-face/i);
  });

  it("carries no CSS custom property, which would export unstyled (D-05)", () => {
    const { svg } = exportSvg(kepan());
    expect(svg).not.toMatch(/var\(--/);
  });

  it("includes a generator note but no local path or history (§12.5)", () => {
    const { svg } = exportSvg(kepan());
    expect(svg).toContain("<desc>Generated by Mapdown</desc>");
    expect(svg).not.toMatch(/\/Users\/|file:\/\/|C:\\/);
  });
});

describe("§12.6 — a label cannot inject markup", () => {
  const hostile = [
    '</text><script>alert(1)</script><text>',
    '"><script>x</script>',
    "Tom & Jerry <b>bold</b>",
    "'quoted' and \"double\""
  ];

  it.each(hostile)("escapes %j rather than emitting it", (label) => {
    const doc = build([
      ["Root", 0],
      [label, 1]
    ]);
    const { svg } = exportSvg(doc);

    expect(svg).not.toMatch(/<script/i);
    // A long label is wrapped across several <tspan>, so the escaped form is not one
    // contiguous run. What must hold is that every markup character arrived as an entity.
    for (const ch of new Set(label.match(/[<>&"']/g) ?? [])) {
      expect(svg).toContain(escapeXml(ch));
    }
    expect(svg).not.toContain(label);
  });

  it("escapes all five XML entities", () => {
    expect(escapeXml(`<&>"'`)).toBe("&lt;&amp;&gt;&quot;&apos;");
  });

  it("produces well-formed XML for the whole 科判 fixture", () => {
    const { svg } = exportSvg(kepan());
    // No DOMParser in the node test environment, so check the two things that actually break
    // an XML parser: unbalanced elements, and a bare & that is not part of an entity.
    for (const tag of ["g", "text", "tspan", "svg", "desc"]) {
      const open = svg.match(new RegExp(`<${tag}[\\s>]`, "g")) ?? [];
      const close = svg.match(new RegExp(`</${tag}>`, "g")) ?? [];
      expect(close.length, `<${tag}> balance`).toBe(open.length);
    }
    expect(svg.replace(/&(amp|lt|gt|quot|apos|#\d+);/g, "")).not.toContain("&");
  });
});

describe("§12.1 / §12.2 — visible state, and only that", () => {
  it("omits collapsed descendants, unlike Markdown which keeps them", () => {
    const doc = build([
      ["Root", 0],
      ["Branch", 1],
      ["Hidden child", 2]
    ]);
    const branchId = getNode(doc, doc.rootId).childIds[0]!;
    const collapsed = applyCommand(doc, { type: "SetCollapsed", nodeId: branchId, collapsed: true }).doc;

    const { svg } = exportSvg(collapsed);
    expect(svg).not.toContain("Hidden child");
    // The distinction §14.4 requires the dialog to explain, asserted rather than assumed.
    expect(exportMarkdown(collapsed)).toContain("Hidden child");
  });

  it("keeps the collapsed count badge, because it is the only sign structure is hidden", () => {
    const doc = build([
      ["Root", 0],
      ["Branch", 1],
      ["A", 2],
      ["B", 2],
      ["C", 2]
    ]);
    const branchId = getNode(doc, doc.rootId).childIds[0]!;
    const collapsed = applyCommand(doc, { type: "SetCollapsed", nodeId: branchId, collapsed: true }).doc;

    const { svg } = exportSvg(collapsed);
    expect(svg).toMatch(/>3<\/text>/);
  });

  it("emits no badge for an expanded node — the minus control is UI, not content", () => {
    const doc = build([
      ["Root", 0],
      ["Branch", 1],
      ["A", 2]
    ]);
    const { svg } = exportSvg(doc);
    expect(svg).not.toMatch(/text-anchor="middle"/);
  });

  it("grows the bounds so a collapsed badge on the outer edge is not clipped", () => {
    const doc = build([
      ["Root", 0],
      ["Branch", 1],
      ["A", 2]
    ]);
    const branchId = getNode(doc, doc.rootId).childIds[0]!;
    const collapsed = applyCommand(doc, { type: "SetCollapsed", nodeId: branchId, collapsed: true }).doc;

    const { svg } = exportSvg(collapsed);
    const viewBox = /viewBox="([^"]+)"/.exec(svg)![1]!.split(" ").map(Number) as number[];
    const cx = Number(/<circle cx="([-\d.]+)"/.exec(svg)![1]);
    expect(cx).toBeGreaterThan(viewBox[0]!);
    expect(cx).toBeLessThan(viewBox[0]! + viewBox[2]!);
  });
});

describe("§12.4 — background", () => {
  it("paints the theme background by default", () => {
    const doc: MindMapDocument = {
      ...kepan(),
      theme: { shapeId: "dark", paletteId: "night-glow", branchColorMode: "single" }
    };
    const { svg } = exportSvg(doc);
    expect(svg).toContain('fill="#16181c"');
  });

  it("omits the background rect entirely when transparent is chosen", () => {
    const { svg } = exportSvg(kepan(), { background: "transparent" });
    expect(svg).not.toMatch(/^<svg[^>]*><desc>[^<]*<\/desc><rect x="[-\d.]+" y="[-\d.]+" width/);
  });
});

describe("theme tokens reach the file (theme.md §2.7)", () => {
  it.each(SHAPES)("$name writes its own node and connector colours", (shape) => {
    const theme = resolveTheme(shape.id, shape.defaultPaletteId);
    const doc: MindMapDocument = {
      ...kepan(),
      theme: { shapeId: shape.id, paletteId: shape.defaultPaletteId, branchColorMode: "single" }
    };
    const { svg } = exportSvg(doc);
    expect(svg).toContain(theme.nodes.root.background);
    expect(svg).toContain(theme.nodes.default.border);
    expect(svg).toContain(theme.connectors.defaultColor);
  });

  it("uses branch colours on connectors when that mode is on", () => {
    const doc: MindMapDocument = {
      ...kepan(),
      theme: { shapeId: "soft-branches", paletteId: "soft-spectrum", branchColorMode: "by-first-level-branch" }
    };
    const { svg } = exportSvg(doc);
    const palette = resolveTheme("soft-branches", "soft-spectrum").branches;
    expect(palette.entries.some((entry) => svg.includes(entry.fill))).toBe(true);
  });

  it("uses the system font stack, never a web font (§12.3)", () => {
    const { svg } = exportSvg(kepan());
    expect(svg).toContain("PingFang SC");
    expect(svg).not.toMatch(/fonts\.googleapis|\.woff/);
  });
});

describe("Theme differentiation steps 1 + 3 — exports carry the authored pairs as literals", () => {
  const soft = resolveTheme("soft-branches", "soft-spectrum");

  it("paints first-level fills from the authored palette pairs in by-first-level mode", () => {
    let doc: MindMapDocument = {
      ...build([
        ["Root", 0],
        ["Alpha", 1],
        ["Beta", 1]
      ]),
      theme: { shapeId: "soft-branches", paletteId: "soft-spectrum", branchColorMode: "by-first-level-branch" }
    };
    // A depth-2 child so the D-24 XMind model is exercised too: deeper nodes carry no tint.
    const alphaId = getNode(doc, doc.rootId).childIds[0]!;
    doc = applyCommand(doc, { type: "CreateChild", parentId: alphaId, text: "grand" }).doc;

    const { svg } = exportSvg(doc);
    const [first, second] = soft.branches.entries;
    expect(svg).toContain(`fill="${first!.fill}"`);
    expect(svg).toContain(`fill="${first!.text}"`);
    expect(svg).toContain(`fill="${second!.fill}"`);
    expect(svg).toContain(`fill="${second!.text}"`);

    // Deeper nodes fall back to the role tokens; only the connector carries the branch colour.
    expect(svg).toContain(`fill="${soft.nodes.default.background}"`);
    expect(svg).toContain(`fill="${soft.nodes.default.text}"`);
  });

  it("carries every palette's fills and authored text colours literally (one text per palette)", () => {
    for (const palette of PALETTES) {
      const doc: MindMapDocument = {
        ...build([
          ["Root", 0],
          ...Array.from({ length: Math.min(palette.entries.length, 8) }, (_, index) => [`B${index}`, 1] as [string, number])
        ]),
        theme: { shapeId: "minimal-light", paletteId: palette.id, branchColorMode: "by-first-level-branch" }
      };
      const { svg } = exportSvg(doc);
      for (const entry of palette.entries) {
        expect(svg, `${palette.id}/${entry.fill}`).toContain(`fill="${entry.fill}"`);
      }
      // One text colour per palette means one literal per palette, never a per-fill choice.
      const texts = new Set(palette.entries.map((entry) => entry.text));
      expect(texts.size).toBe(1);
      for (const text of texts) expect(svg).toContain(`fill="${text}"`);
    }
  });

  it("keeps single-mode node fills exactly as the role tokens paint them", () => {
    const doc: MindMapDocument = {
      ...build([
        ["Root", 0],
        ["Alpha", 1]
      ]),
      theme: { shapeId: "soft-branches", paletteId: "soft-spectrum", branchColorMode: "single" }
    };
    const { svg } = exportSvg(doc);
    expect(svg).toContain(`fill="${soft.nodes.level1.background}"`);
    expect(svg).toContain(`fill="${soft.nodes.level1.text}"`);
  });
});

describe("CJK survives serialisation", () => {
  it("writes Han text as text, not paths", () => {
    const { svg } = exportSvg(kepan());
    expect(svg).toContain("暇满难得");
    expect(svg).toContain("丁六 思维死缘无定而修无常");
    expect(svg).not.toMatch(/<path[^>]*d="M[^"]*"[^>]*fill="#1c1e21"/);
  });

  it("emits one tspan per measured line, so wrapping matches the editor", () => {
    const long = "思维死缘无定而修无常，思维猛励希求而修无常，思维各种喻义而修无常";
    const doc = build([
      ["Root", 0],
      [long, 1]
    ]);
    const { svg } = exportSvg(doc);
    const tspans = svg.match(/<tspan/g) ?? [];
    expect(tspans.length).toBeGreaterThan(2); // root's one line plus a wrapped label
  });
});

describe("§13.2 — PNG scale is reduced rather than producing a blank image", () => {
  it("keeps the requested scale for an ordinary map", () => {
    expect(resolveScale(900, 600, 2)).toBe(2);
    expect(resolveScale(900, 600, 3)).toBe(3);
  });

  it("steps down when the pixel area would exceed what a canvas can hold", () => {
    // 4000 x 3000 at 3x is 36000 x 27000 — far past the limit.
    expect(resolveScale(4000, 3000, 3)).toBeLessThan(3);
  });

  it("never returns a scale whose canvas exceeds the area limit", () => {
    for (const [w, h] of [
      [900, 600],
      [4000, 3000],
      [12000, 9000],
      [30000, 20000]
    ] as const) {
      const scale = resolveScale(w, h, 3);
      if (scale === null) continue; // too large at any scale — reported, not faked
      const pixels = pixelDimensions(w, h, scale);
      expect(pixels.width * pixels.height).toBeLessThanOrEqual(MAX_CANVAS_AREA);
    }
  });

  it("reports impossibility rather than returning a scale that still cannot be drawn", () => {
    // 40000 x 40000 exceeds the canvas limit even at 1x. Returning 1 would promise an image
    // that comes back blank; §13.2 forbids exactly that.
    expect(resolveScale(40000, 40000, 3)).toBeNull();
  });
});
