import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import process from "node:process";
import { resolveMapdownWebOriginForBuild } from "./src/cloud/build-origin";

export default defineConfig(() => {
  const webOrigin = resolveMapdownWebOriginForBuild(process.env);

  return {
    plugins: [react()],
    server: { port: 5174 },
    build: {
      outDir: "dist",
      rollupOptions: {
        /**
         * Two entries: the app, and the published-map viewer (D-32).
         *
         * The viewer is referenced from HTML generated by a Pages Function, which cannot read a
         * build manifest, so its filename must be stable across builds. The app keeps content
         * hashing. Modules both entries use — `layout/`, `theme/`, the viewport helper — end up
         * in a shared chunk, which is the point: the reader and the author run the same layout
         * code. Editor and storage modules are reachable from the app entry only, and
         * `src/viewer/import-boundary.test.ts` keeps it that way.
         */
        input: {
          index: "index.html",
          viewer: "src/viewer/main.tsx"
        },
        output: {
          entryFileNames: (chunk) =>
            chunk.name === "viewer" ? "published/viewer.js" : "assets/[name]-[hash].js"
        }
      }
    },
    define: webOrigin
      ? { "import.meta.env.VITE_WEB_ORIGIN": JSON.stringify(webOrigin) }
      : undefined
  };
});
