/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: fce6b7e7547aa2c59d71d022b62a56cf)
declare namespace Cloudflare {
	interface Env {
		R2: R2Bucket;
		DB: D1Database;
		WEB_ORIGIN: "https://bcailab.com";
		MAPDOWN_ORIGIN: "https://map.bcailab.com";
		PUBLISHED_ORIGIN: "https://share.bcailab.com";
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WEB_ORIGIN" | "MAPDOWN_ORIGIN" | "PUBLISHED_ORIGIN">> {}
}
